classdef StyleCatalog
    % StyleCatalog 预定义终端区管理样式目录
    %
    %   提供 E0/E1 实验所需的终端样式配置。
    %   后续 Phase 可扩展更多样式。

    methods (Static)
        function style = fixedNorth(corridorIds)
            % E0 样式：固定北向定位点接口
            %   只允许北向(N)和备用(B)走廊连接
            %   容量和延误参数与 fixedSouth 完全相同
            arguments
                corridorIds (:,1) string = ["N"; "B"]
            end
            style = uam.core.TerminalStyleConfig('fixed_north', ...
                'feasibleCorridors', corridorIds, ...
                'padCount', 2, ...
                'waitingSlots', 4, ...
                'serviceTime', 120, ...
                'ringRadiusNm', 0.3, ...
                'approachLengthNm', 0.8, ...
                'footprintBlock', string.empty, ...
                'noiseIndex', 1.0, ...
                'populationExposure', 0);
        end

        function style = fixedSouth(corridorIds)
            % E0 样式：固定南向定位点接口
            %   只允许南向(S)和备用(B)走廊连接
            %   容量和延误参数与 fixedNorth 完全相同
            arguments
                corridorIds (:,1) string = ["S"; "B"]
            end
            style = uam.core.TerminalStyleConfig('fixed_south', ...
                'feasibleCorridors', corridorIds, ...
                'padCount', 2, ...
                'waitingSlots', 4, ...
                'serviceTime', 120, ...
                'ringRadiusNm', 0.3, ...
                'approachLengthNm', 0.8, ...
                'footprintBlock', string.empty, ...
                'noiseIndex', 1.0, ...
                'populationExposure', 0);
        end

        function style = compactRing(corridorIds)
            % E1 样式：紧凑环形等待/接入
            %   所有走廊均可连接，空域脚印小，不阻塞外部走廊
            arguments
                corridorIds (:,1) string = ["C"; "N"; "S"]
            end
            style = uam.core.TerminalStyleConfig('compact_ring', ...
                'feasibleCorridors', corridorIds, ...
                'padCount', 2, ...
                'waitingSlots', 4, ...
                'serviceTime', 120, ...
                'ringRadiusNm', 0.3, ...
                'approachLengthNm', 0.5, ...
                'footprintBlock', string.empty, ...
                'noiseIndex', 1.0, ...
                'populationExposure', 0);
        end

        function style = wideRing(corridorIds, blockedCorridors)
            % E1 样式：宽环形等待/接入
            %   所有走廊名义上可连接，但空域脚印大，阻塞中心走廊(C)
            arguments
                corridorIds (:,1) string = ["C"; "N"; "S"]
                blockedCorridors (:,1) string = "C"
            end
            style = uam.core.TerminalStyleConfig('wide_ring', ...
                'feasibleCorridors', corridorIds, ...
                'padCount', 2, ...
                'waitingSlots', 4, ...
                'serviceTime', 120, ...
                'ringRadiusNm', 1.0, ...
                'approachLengthNm', 1.5, ...
                'footprintBlock', blockedCorridors, ...
                'noiseIndex', 1.5, ...
                'populationExposure', 50);
        end
    end
end
